apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubectl
  namespace: kube-system
  labels:
    app: kubectl
spec:
  selector:
    matchLabels:
      app: kubectl
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: kubectl
      labels:
        app: kubectl
    spec:
      serviceAccountName: kubectl-admin
      containers:
      - name: kubectl
        image: docker.io/imroc/kubectl:latest
        imagePullPolicy: Always

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-admin
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubectl-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubectl-admin
subjects:
- kind: ServiceAccount
  name: kubectl-admin
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kubectl-admin
  apiGroup: rbac.authorization.k8s.io
